version: '3.7'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_ENV: production
        CACHE_TTL: 43200
        YOUTUBE_API_KEY: AIzaSyDCWlChZ0CLy9N-Bp1_aSkxLQLaj88K4aU
        YOUTUBE_CHANNEL_ID: UC8GoStv0qTHZLikuiuSWvAg
    ports:
      - 3000:3000


