version: '3.7'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_ENV: production
        CACHE_TTL: 43200
        YOUTUBE_API_KEY: YOUR-API-KEY
        YOUTUBE_CHANNEL_ID: YOUR-CHANNEL-ID
    ports:
      - 3000:3000


